### ISSUE TITLE
모든 글 리스팅 기능

### ISSUE THREAD

**Issue by 0andme** [0andme/shinhan-js-toy#3]
모든 글을 리스팅하기 위한 index.html 을 만들고, 백엔드에 글을 가져오기 위한 GET 요청을 보내고, 이를 토대로 글을 보여주는 기능을 구현해주세요.

- [x] 해당 페이지에서 특정한 글을 클릭하면 모달 형태로 세부 내용이 표시되도록 구현해주세요. #6 
- [x] 해당 페이지에서 글쓰기 버튼을 클릭하면 글을 쓰기 위한 모달이 표시되도록 구현해주세요.  #5 
- [x]  해당 페이지에서 카테고리 별로 글을 필터링할 수 있도록, 카테고리 선택 메뉴를 구현해주세요. #4
